export const PUT_EXAME_REQUESTED = 'PUT_EXAME_REQUESTED';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const POST_CONSULTAS_REQUESTED = 'POST_CONSULTAS_REQUESTED';
export const POST_CONSULTAS_SUCCESS = 'POST_CONSULTAS_SUCCESS';
export const POST_CONSULTAS_FAILED = 'POST_CONSULTAS_FAILED';
export const PUT_CONSULTAS_REQUESTED = 'PUT_CONSULTAS_REQUESTED';
export const PUT_CONSULTAS_SUCCESS = 'PUT_CONSULTAS_SUCCESS';
export const PUT_CONSULTAS_FAILED = 'PUT_CONSULTAS_FAILED';
export const GET_CONSULTAS_REQUESTED = 'GET_CONSULTAS_REQUESTED';
export const GET_CONSULTAS_SUCCESS = 'GET_CONSULTAS_SUCCESS';
export const GET_CONSULTAS_FAILED = 'GET_CONSULTAS_FAILED';
export const DELETE_CONSULTAS_REQUESTED = 'DELETE_CONSULTAS_REQUESTED';

export const POST_EXAME_REQUESTED = 'POST_EXAME_REQUESTED';
export const POST_EXAME_SUCCESS = 'POST_EXAME_SUCCESS';
export const POST_EXAME_FAILED = 'POST_EXAME_FAILED';
export const GET_EXAME_REQUESTED = 'GET_EXAME_REQUESTED';
export const GET_EXAME_SUCCESS = 'GET_EXAME_SUCCESS';
export const GET_EXAME_FAILED = 'GET_EXAME_FAILED';
export const DELETE_EXAME_REQUESTED = 'DELETE_EXAME_REQUESTED'

export const POST_CIRURGIA_REQUESTED = 'POST_CIRURGIA_REQUESTED';
export const POST_CIRURGIA_SUCCESS = 'POST_CIRURGIA_SUCCESS';
export const POST_CIRURGIA_FAILED = 'POST_CIRURGIA_FAILED';
export const GET_CIRURGIA_REQUESTED = 'GET_CIRURGIA_REQUESTED';
export const GET_CIRURGIA_SUCCESS = 'GET_CIRURGIA_SUCCESS';
export const GET_CIRURGIA_FAILED = 'GET_CIRURGIA_FAILED';
export const GET_CIRURGIA_BY_USUARIO_REQUESTED = 'GET_CIRURGIA_BY_USUARIO_REQUESTED';
export const GET_CIRURGIA_BY_USUARIO_SUCCESS = 'GET_CIRURGIA_BY_USUARIO_SUCCESS';
export const GET_CIRURGIA_BY_USUARIO_FAILED = 'GET_CIRURGIA_BY_USUARIO_FAILED';
export const PUT_CIRURGIA_REQUESTED = 'PUT_CIRURGIA_REQUESTED';
export const PUT_CIRURGIA_SUCCESS = 'PUT_CIRURGIA_SUCCESS';
export const PUT_CIRURGIA_FAILED = 'PUT_CIRURGIA_FAILED';
export const DELETE_CIRURGIA_REQUESTED = 'DELETE_CIRURGIA_REQUESTED'

export const GET_PROFISSIONAIS_REQUESTED = 'GET_PROFISSIONAIS_REQUESTED';
export const GET_PROFISSIONAIS_SUCCESS = 'GET_PROFISSIONAIS_SUCCESS';
export const GET_PROFISSIONAIS_FAILED = 'GET_PROFISSIONAIS_FAILED';
export const GET_GUIAS_REQUESTED = 'GET_GUIAS_REQUESTED';
export const GET_GUIAS_SUCCESS = 'GET_GUIAS_SUCCESS';
export const GET_GUIAS_FAILED = 'GET_GUIAS_FAILED';
export const DELETE_GUIAS_REQUESTED = 'DELETE_GUIAS_REQUESTED';
